/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'HelloMsg'
 * message type.
 */

public class HelloMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 6;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = -1;

    /** Create a new HelloMsg of size 6. */
    public HelloMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new HelloMsg of the given data_length. */
    public HelloMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HelloMsg with the given data_length
     * and base offset.
     */
    public HelloMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HelloMsg using the given byte array
     * as backing store.
     */
    public HelloMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HelloMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public HelloMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HelloMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public HelloMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HelloMsg embedded in the given message
     * at the given base offset.
     */
    public HelloMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HelloMsg embedded in the given message
     * at the given base offset and length.
     */
    public HelloMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <HelloMsg> \n";
      try {
        s += "  [id=0x"+Long.toHexString(get_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [t=0x"+Long.toHexString(get_t())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: id
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'id' is signed (false).
     */
    public static boolean isSigned_id() {
        return false;
    }

    /**
     * Return whether the field 'id' is an array (false).
     */
    public static boolean isArray_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'id'
     */
    public static int offset_id() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'id'
     */
    public static int offsetBits_id() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'id'
     */
    public int get_id() {
        return (int)getUIntBEElement(offsetBits_id(), 16);
    }

    /**
     * Set the value of the field 'id'
     */
    public void set_id(int value) {
        setUIntBEElement(offsetBits_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'id'
     */
    public static int size_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'id'
     */
    public static int sizeBits_id() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: t
    //   Field type: long, unsigned
    //   Offset (bits): 16
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 't' is signed (false).
     */
    public static boolean isSigned_t() {
        return false;
    }

    /**
     * Return whether the field 't' is an array (false).
     */
    public static boolean isArray_t() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 't'
     */
    public static int offset_t() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 't'
     */
    public static int offsetBits_t() {
        return 16;
    }

    /**
     * Return the value (as a long) of the field 't'
     */
    public long get_t() {
        return (long)getUIntBEElement(offsetBits_t(), 32);
    }

    /**
     * Set the value of the field 't'
     */
    public void set_t(long value) {
        setUIntBEElement(offsetBits_t(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 't'
     */
    public static int size_t() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 't'
     */
    public static int sizeBits_t() {
        return 32;
    }

}
